[application]

# App (Project) Name
name = "hocg-deck-convert"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
public_dir = "public"

[web.app]

# HTML title tag content
title = "hololive OCG Deck Converter"

# for GitHub Pages
base_path = "hocg-deck-convert"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
